<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DEADSKY.Core\DEADSKY.Core.csproj" />
    <ProjectReference Include="..\DEADSKY.AI\DEADSKY.AI.csproj" />
    <ProjectReference Include="..\DEADSKY.Audio\DEADSKY.Audio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="2.88.9" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\..\DEADSKY.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
